[bans]
multiple-versions = "warn"
wildcards = "deny"

[licenses]
unlicensed = "deny"
allow = ["MIT", "Apache-2.0", "BSD-3-Clause", "BSD-2-Clause", "ISC", "Zlib", "Unicode-DFS-2016"]
copyleft = "warn"

[sources]
unknown-registry = "deny"
unknown-git = "warn"
